package com.gw.android.first_components.my_components.user;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User extends com.gw.android.first_components.my_fragment.ComponentSimpleModel  {

    private Long id;
    private Long targetId;
    private Long serverId;
    private String usuario;
    private String sobrenome;
    private String escolaridade;
    private String curso;
    private String instituicao;
    private String ocupacao;
    private String email;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Long targetId, Long serverId, String usuario, String sobrenome, String escolaridade, String curso, String instituicao, String ocupacao, String email) {
        this.id = id;
        this.targetId = targetId;
        this.serverId = serverId;
        this.usuario = usuario;
        this.sobrenome = sobrenome;
        this.escolaridade = escolaridade;
        this.curso = curso;
        this.instituicao = instituicao;
        this.ocupacao = ocupacao;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getSobrenome() {
        return sobrenome;
    }

    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    public String getEscolaridade() {
        return escolaridade;
    }

    public void setEscolaridade(String escolaridade) {
        this.escolaridade = escolaridade;
    }

    public String getCurso() {
        return curso;
    }

    public void setCurso(String curso) {
        this.curso = curso;
    }

    public String getInstituicao() {
        return instituicao;
    }

    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }

    public String getOcupacao() {
        return ocupacao;
    }

    public void setOcupacao(String ocupacao) {
        this.ocupacao = ocupacao;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
