package my_components.gps;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COORDINATES.
 */
public class Coordinates extends com.example.my_fragment.ComponentSimpleModel  {

    private Long id;
    private Long targetId;
    private long latitude;
    private long longitude;

    public Coordinates() {
    }

    public Coordinates(Long id) {
        this.id = id;
    }

    public Coordinates(Long id, Long targetId, long latitude, long longitude) {
        this.id = id;
        this.targetId = targetId;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    public long getLatitude() {
        return latitude;
    }

    public void setLatitude(long latitude) {
        this.latitude = latitude;
    }

    public long getLongitude() {
        return longitude;
    }

    public void setLongitude(long longitude) {
        this.longitude = longitude;
    }

}
