package com.gw.android.first_components.my_components.comment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMMENT.
 */
public class Comment extends
		com.gw.android.first_components.my_fragment.ComponentSimpleModel {

	private Long id;
	private Long targetId;
	private Long serverId;
	/** Not-null value. */
	private String text;
	private java.util.Date date;
	private String usuario;

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Comment() {
	}

	public Comment(Long id) {
		this.id = id;
	}

	public Comment(Long id, Long targetId, Long serverId, String text,
			java.util.Date date) {
		this.id = id;
		this.targetId = targetId;
		this.serverId = serverId;
		this.text = text;
		this.date = date;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getTargetId() {
		return targetId;
	}

	public void setTargetId(Long targetId) {
		this.targetId = targetId;
	}

	public Long getServerId() {
		return serverId;
	}

	public void setServerId(Long serverId) {
		this.serverId = serverId;
	}

	/** Not-null value. */
	public String getText() {
		return text;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setText(String text) {
		this.text = text;
	}

	public java.util.Date getDate() {
		return date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

}
