package my_activities;

import java.util.ArrayList;
import java.util.List;

import my_components.CommentListGUI;
import my_components.CommentSendGUI;
import my_components.PhotoGUI;
import android.os.Bundle;
import android.widget.LinearLayout;
import android.widget.Toast;

import com.example.firstcomponents.R;
import com.example.my_fragment.ComponentSimpleModel;
import com.example.my_fragment.MyComponent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RATING2_COMMENT2_PHOTO.
 */
public class Rating2Comment2Photo  {
	
	
	
    private Long id;
    private Long sourceId;
    private Long targetId;

    public Rating2Comment2Photo() {
    }

    public Rating2Comment2Photo(Long id) {
        this.id = id;
    }

    public Rating2Comment2Photo(Long id, Long sourceId, Long targetId) {
        this.id = id;
        this.sourceId = sourceId;
        this.targetId = targetId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSourceId() {
        return sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

	

	
}
