package my_activities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RATING2_COMMENT2_PHOTO.
 */
public class Rating2Comment2Photo extends com.example.my_fragment.MyActivity  {

    private Long id;
    private Long sourceId;
    private Long targetId;

    public Rating2Comment2Photo() {
    }

    public Rating2Comment2Photo(Long id) {
        this.id = id;
    }

    public Rating2Comment2Photo(Long id, Long sourceId, Long targetId) {
        this.id = id;
        this.sourceId = sourceId;
        this.targetId = targetId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSourceId() {
        return sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

	@Override
	public void configurarTargets() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void instanciarComponents() {
		// TODO Auto-generated method stub
		
	}

}
