package com.gw.android.my_components.request;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REQUEST.
 */
public class Request extends com.gw.android.my_fragment.ComponentSimpleModel  {

    private Long id;
    private Long targetId;
    /** Not-null value. */
    private String url;
    /** Not-null value. */
    private String type;
    private String keyValuePairs;

    public Request() {
    }

    public Request(Long id) {
        this.id = id;
    }

    public Request(Long id, Long targetId, String url, String type, String keyValuePairs) {
        this.id = id;
        this.targetId = targetId;
        this.url = url;
        this.type = type;
        this.keyValuePairs = keyValuePairs;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public String getKeyValuePairs() {
        return keyValuePairs;
    }

    public void setKeyValuePairs(String keyValuePairs) {
        this.keyValuePairs = keyValuePairs;
    }

}
