package my_components.rating2comment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RATING_TO_COMMENT.
 */
public class RatingToComment extends com.example.my_fragment.ComponentSimpleModel  {

    private Long id;
    private Long targetId;

    public RatingToComment() {
    }

    public RatingToComment(Long id) {
        this.id = id;
    }

    public RatingToComment(Long id, Long targetId) {
        this.id = id;
        this.targetId = targetId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

	@Override
	public void save() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void restore() {
		// TODO Auto-generated method stub
		
	}

}
