package database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import my_components.Comment;
import my_components.Photo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig commentDaoConfig;
	private final DaoConfig photoDaoConfig;

	private final CommentDao commentDao;
	private final PhotoDao photoDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);

		commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
		commentDaoConfig.initIdentityScope(type);

		photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
		photoDaoConfig.initIdentityScope(type);

		commentDao = new CommentDao(commentDaoConfig, this);
		photoDao = new PhotoDao(photoDaoConfig, this);

		registerDao(Comment.class, commentDao);
		registerDao(Photo.class, photoDao);
	}

	public void clear() {
		commentDaoConfig.getIdentityScope().clear();
		photoDaoConfig.getIdentityScope().clear();
	}

	public CommentDao getCommentDao() {
		return commentDao;
	}

	public PhotoDao getPhotoDao() {
		return photoDao;
	}

}
