package com.gw.android.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import com.gw.android.my_components.binomio.Binomio;
import com.gw.android.my_components.binomio.BinomioDao;
import com.gw.android.my_components.comment.Comment;
import com.gw.android.my_components.comment.CommentDao;
import com.gw.android.my_components.faq.Faq;
import com.gw.android.my_components.faq.FaqDao;
import com.gw.android.my_components.gps.Coordinates;
import com.gw.android.my_components.gps.CoordinatesDao;
import com.gw.android.my_components.photo.Photo;
import com.gw.android.my_components.photo.PhotoDao;
import com.gw.android.my_components.rating.Rating;
import com.gw.android.my_components.rating.RatingDao;
import com.gw.android.my_components.rating2comment.RatingToComment;
import com.gw.android.my_components.rating2comment.RatingToCommentDao;
import com.gw.android.my_components.tag.Tag;
import com.gw.android.my_components.tag.TagDao;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commentDaoConfig;
    private final DaoConfig photoDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig binomioDaoConfig;
    private final DaoConfig coordinatesDaoConfig;
    private final DaoConfig faqDaoConfig;
    private final DaoConfig ratingDaoConfig;
    private final DaoConfig ratingToCommentDaoConfig;

    private final CommentDao commentDao;
    private final PhotoDao photoDao;
    private final TagDao tagDao;
    private final BinomioDao binomioDao;
    private final CoordinatesDao coordinatesDao;
    private final FaqDao faqDao;
    private final RatingDao ratingDao;
    private final RatingToCommentDao ratingToCommentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        binomioDaoConfig = daoConfigMap.get(BinomioDao.class).clone();
        binomioDaoConfig.initIdentityScope(type);

        coordinatesDaoConfig = daoConfigMap.get(CoordinatesDao.class).clone();
        coordinatesDaoConfig.initIdentityScope(type);

        faqDaoConfig = daoConfigMap.get(FaqDao.class).clone();
        faqDaoConfig.initIdentityScope(type);

        ratingDaoConfig = daoConfigMap.get(RatingDao.class).clone();
        ratingDaoConfig.initIdentityScope(type);

        ratingToCommentDaoConfig = daoConfigMap.get(RatingToCommentDao.class).clone();
        ratingToCommentDaoConfig.initIdentityScope(type);

        commentDao = new CommentDao(commentDaoConfig, this);
        photoDao = new PhotoDao(photoDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        binomioDao = new BinomioDao(binomioDaoConfig, this);
        coordinatesDao = new CoordinatesDao(coordinatesDaoConfig, this);
        faqDao = new FaqDao(faqDaoConfig, this);
        ratingDao = new RatingDao(ratingDaoConfig, this);
        ratingToCommentDao = new RatingToCommentDao(ratingToCommentDaoConfig, this);

        registerDao(Comment.class, commentDao);
        registerDao(Photo.class, photoDao);
        registerDao(Tag.class, tagDao);
        registerDao(Binomio.class, binomioDao);
        registerDao(Coordinates.class, coordinatesDao);
        registerDao(Faq.class, faqDao);
        registerDao(Rating.class, ratingDao);
        registerDao(RatingToComment.class, ratingToCommentDao);
    }
    
    public void clear() {
        commentDaoConfig.getIdentityScope().clear();
        photoDaoConfig.getIdentityScope().clear();
        tagDaoConfig.getIdentityScope().clear();
        binomioDaoConfig.getIdentityScope().clear();
        coordinatesDaoConfig.getIdentityScope().clear();
        faqDaoConfig.getIdentityScope().clear();
        ratingDaoConfig.getIdentityScope().clear();
        ratingToCommentDaoConfig.getIdentityScope().clear();
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public BinomioDao getBinomioDao() {
        return binomioDao;
    }

    public CoordinatesDao getCoordinatesDao() {
        return coordinatesDao;
    }

    public FaqDao getFaqDao() {
        return faqDao;
    }

    public RatingDao getRatingDao() {
        return ratingDao;
    }

    public RatingToCommentDao getRatingToCommentDao() {
        return ratingToCommentDao;
    }

}
