package com.gw.android.first_components.my_components.photo;

import com.gw.android.R;
import com.gw.android.first_components.my_components.gps.Coordinates;
import com.gw.android.first_components.my_components.tracker.Trackable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PHOTO.
 */
public class Photo extends
		com.gw.android.first_components.my_fragment.ComponentSimpleModel implements Trackable{

	private Long id;
	private Long targetId;
	private Long serverId;
	private Boolean isThumb;
	private byte[] photoBytes;
	private String text;
	private java.util.Date date;

	public Photo() {
	}

	public Photo(Long id) {
		this.id = id;
	}

	public Photo(Long id, Long targetId, Long serverId, Boolean isThumb,
			byte[] photoBytes, String text, java.util.Date date) {
		this.id = id;
		this.targetId = targetId;
		this.serverId = serverId;
		this.isThumb = isThumb;
		this.photoBytes = photoBytes;
		this.text = text;
		this.date = date;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getTargetId() {
		return targetId;
	}

	public void setTargetId(Long targetId) {
		this.targetId = targetId;
	}

	public Long getServerId() {
		return serverId;
	}

	public void setServerId(Long serverId) {
		this.serverId = serverId;
	}

	public Boolean getIsThumb() {
		return isThumb;
	}

	public void setIsThumb(Boolean isThumb) {
		this.isThumb = isThumb;
	}

	public byte[] getPhotoBytes() {
		return photoBytes;
	}

	public void setPhotoBytes(byte[] photoBytes) {
		this.photoBytes = photoBytes;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public java.util.Date getDate() {
		return date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return "One Photo";
	}

	@Override
	public String getComponentType() {
		// TODO Auto-generated method stub
		return "Photo View";
	}

	@Override
	public int getIconResource() {
		// TODO Auto-generated method stub
		return R.drawable.picture_small;
	}

	@Override
	public Coordinates getCoordinates() {
		// TODO Auto-generated method stub
		return new Coordinates(null, null, null, -20.4, -40.30, null, null,
				null);
	}

	@Override
	public void doTrackableRequest() {
		// TODO Auto-generated method stub

	}

}
